import os
import time
import pandas as pd
import requests
from bs4 import BeautifulSoup

class DropPointScraper:
    def __init__(self, output_dir):
        self.session = requests.Session()
        self.token = None
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def set_token(self):
        url = 'http://www.jet.co.id/droppoint'
        res = self.session.get(url)
        soup = BeautifulSoup(res.text, "lxml")
        self.token = soup.find('input', attrs = {'name' : '_token'})['value']

    def get_cities(self):
        return ["ACEH BARAT DAYA","ACEH SELATAN","AMBARAWA","AMBON","AMUNTAI","ANAMBAS","ARFAK","ARGAMAKMUR","ASAHAN","ASMAT","BAA","BADUNG","BAJAWA","BALANGAN","BALIKPAPAN","BANDA ACEH","BANDAR LAMPUNG","BANDUNG","BANGGAI","BANGGAI KEPULAUAN","BANGGAI LAUT","BANGKA","BANGKA BARAT","BANGKA SELATAN","BANGKA TENGAH","BANGKALAN","BANGKO","BANGLI","BANJAR","BANJARBARU","BANJARMASIN","BANJARNEGARA","BANTAENG","BANTUL","BANYUASIN","BANYUMAS","BANYUWANGI","BARRU","BATAM","BATANG","BATANG HARI","BATU","BATU BARA","BATURAJA","BAU-BAU","BEKASI","BELITUNG","BELITUNG TIMUR","BELU","BENGKALIS","BENGKAYANG","BENGKULU","BENGKULU TENGAH","BERAU","BIAK","BIMA","BINJAI","BINTAN","BIREUEN","BITUNG","BLITAR","BLORA","BOGOR","BOJONEGORO","BOLAANG MONGONDOW","BOLAANG MONGONDOW TIMUR","BOLAANG MONGONDOW UTARA","BOMBANA","BONDOWOSO","BONE","BONTANG","BORONG","BOVEN DIGOEL","BOYOLALI","BREBES","BUKIT TINGGI","BULELENG","BULUKUMBA","BULUNGAN","BUNTOK","BUOL","BURU","BURU SELATAN","BUTON","BUTON UTARA","CALANG","CARUBAN","CEPU","CIAMIS","CIANJUR","CIKARANG","CILACAP","CILEGON","CIREBON","DAIRI","DATARAN HUNIMOA","DEIYAI","DELI SERDANG","DEMAK","DENPASAR","DEPOK","DHAMASRAYA","DOGIYAI","DOMPU","DONGGALA","DUMAI","EMPAT LAWANG","ENDE","ENREKANG","FAK-FAK","GARUT","GAYO LUES","GIANYAR","GORONTALO","GORONTALO UTARA","GOWA","GRESIK","GROBOGAN","GUNUNG SITOLI","HALMAHERA BARAT","HALMAHERA SELATAN","HALMAHERA TENGAH","HALMAHERA TIMUR","HALMAHERA UTARA","HULU SUNGAI TENGAH","HUMBANG HASUNDUTAN","IDI RAYEUK","INDRAGIRI HILIR","INDRAGIRI HULU","INDRAMAYU","INTAN JAYA","JAKARTA","JAMBI","JANTHO","JAYAPURA","JAYAWIJAYA","JEMBER","JEMBRANA","JENEPONTO","JEPARA","JOMBANG","KAB.BIMA","KAB.GORONTALO","KAB.SERANG","KAB.SORONG","KAIMANA","KALABAHI","KAMPAR","KANDANGAN","KAPUAS HULU","KARANG ANYAR","KARANG ASEM","KARAWANG","KARIMUN","KARO","KATINGAN","KAUR","KAYONG UTARA","KAYU AGUNG","KEBUMEN","KEDIRI","KEEROM","KENDAL","KENDARI","KEPAHIANG","KEPANJEN","KEPULAUAN ARU","KEPULAUAN MERANTI","KEPULAUAN SIAU","KEPULAUAN TALAUD","KEPULAUAN TALIABU","KERINCI","KETAPANG","KLATEN","KLUNGKUNG","KOLAKA","KOLAKA UTARA","KONAWE","KONAWE SELATAN","KONAWE UTARA","KOTA MOBAGU","KOTABARU","KOTAWARINGIN TIMUR","KUALA KAPUAS","KUALA KURUN","KUALA PEMBUANG","KUALA SIMPANG","KUATAN SINGINGI","KUBURAYA","KUDUS","KULON PROGO","KUNINGAN","KUPANG","KUTACANE","KUTAI TIMUR","LABUAN BAJO","LABUAN BATU","LABUHAN BATU SELATAN","LABUHAN BATU UTARA","LAHAT","LAMANDAU","LAMONGAN","LAMPUNG BARAT","LAMPUNG SELATAN","LAMPUNG TENGAH","LAMPUNG TIMUR","LAMPUNG UTARA","LANGKAT","LANGSA","LANNY JAYA","LARANTUKA","LEBAK","LEBONG","LEWOLEBA","LHOKSEUMAWE","LHOKSUKON","LINGGA","LOMBOK","LOMBOK BARAT","LOMBOK UTARA","LUBUK BASUNG","LUBUK LINGGAU","LUBUK PAKAM","LUMAJANG","LUWU","MADIUN","MAGELANG","MAGETAN","MAJALENGKA","MAJENE","MAKASSAR","MALAKA","MALANG","MALILI","MALINAU","MALUKU BARAT DAYA","MALUKU TENGAH","MALUKU TENGGARA","MALUKU TENGGARA BARAT","MAMASA","MAMBERAMO RAYA","MAMBERAMO TENGAH","MAMUJU","MANADO","MANDAILING NATAL","MANNA","MANOKWARI","MANOKWARI SELATAN","MAPPI","MARABAHAN","MARISA","MAROS","MARTAPURA(BANJARMASIN)","MASAMBA","MATARAM","MAUMERE","MAYBRAT","MBAY","MEDAN","MELAWI","MEMPAWAH","MENTAWAI","MERAUKE","MESUJI","METRO","MEULABOH","MEUREUDU","MIMIKA","MINAHASA","MINAHASA SELATAN","MINAHASA TENGGARA","MINAHASA UTARA","MOJOKERTO","MOJOSARI","MONGONDOW SELATAN","MOROWALI","MOROWALI UTARA","MUARA BADAK","MUARA BUNGO","MUARA DUA","MUARA ENIM","MUARA TEWEH","MUARO JAMBI","MUKO-MUKO","MUNA","MUNGKID","MURUNG RAYA","MUSI RAWAS","MUSI RAWAS UTARA","NABIRE","NAGAN RAYA","NATUNA","NDUGA","NGABANG","NGANJUK","NGASEM","NGAWI","NIAS BARAT","NIAS SELATAN","NIAS UTARA","NUNUKAN","OELAMASI","OGAN ILIR","OGAN KOMERING ULU TIMUR","PACITAN","PADANG","PADANG LAWAS","PADANG LAWAS UTARA","PADANG PANJANG","PADANG PARIAMAN","PAGAR ALAM","PAITON","PAKPAK BHARAT","PALANGKARAYA","PALARAN","PALEMBANG","PALOPO","PALU","PAMEKASAN","PANDAAN","PANDEGLANG","PANGANDARAN","PANGKAJENE","PANGKAL PINANG","PANGKALANBUN","PANIAI","PARE PARE","PARIAMAN","PARIGI MOUTONG","PASAMAN","PASAMAN BARAT","PASANG KAYU","PASER","PASURUAN","PATI","PAYAKUMBUH","PEGUNUNGAN BINTANG","PEKALONGAN","PEKANBARU","PELABUHAN RATU","PELALAWAN","PEMALANG","PEMATANG SIANTAR","PENAJAM","PENUKAL ABAB LEMATANG ILIR","PESAWARAN","PESISIR BARAT","PESISIR SELATAN","PINRANG","POLEWALI","PONOROGO","PONTIANAK","POSO","PRABUMULIH","PRINGSEWU","PROBOLINGGO","PULANG PISAU","PULAU MOROTAI","PUNCAK","PUNCAK JAYA","PURBALINGGA","PURWAKARTA","PURWOREJO","RAJA AMPAT","RANTAU(BANJARMASIN)","REJANG LEBONG","REMBANG","ROKAN HILIR","ROKAN HULU","RUTENG","SABANG","SABU RAIJUA","SALATIGA","SAMARINDA","SAMBAS","SAMOSIR","SAMPANG","SANANA","SANGGAU","SARMI","SAROLANGUN","SAWAH LUNTO","SEKADAU","SEKAYU","SELAYAR","SELONG","SELUMA","SEMARANG","SENDAWAR","SENTANI","SERAM BAGIAN BARAT","SERAM BAGIAN TIMUR","SERANG","SERDANG BEDAGAI","SERUI","SIAK","SIBOLGA","SIDENRENG RAPANG","SIDOARJO","SIGI","SIGLI","SIJUNJUNG","SIMALUNGUN","SIMPANG TIGA REDELONG","SINABANG","SINGKAWANG","SINGKIL","SINJAI","SINTANG","SIPIROK","SITUBONDO","SLAWI","SLEMAN","SOE","SOLO","SOLOK","SOLOK SELATAN","SOPPENG","SORENDIWERI","SORONG","SORONG SELATAN","SRAGEN","STABAT","SUBANG","SUBULUSSALAM","SUKABUMI","SUKAMARA","SUKOHARJO","SUMBAWA BARAT","SUMBAWA BESAR","SUMEDANG","SUMENEP","SUNGAI PENUH","SURABAYA","SUWAWA","TABALONG","TABANAN","TAHUNA","TAKALAR","TAKENGON","TAMBOLAKA","TAMBRAUW","TAMIANG LAYANG","TANA TIDUNG","TANA TORAJA","TANAH BUMBU","TANAH DATAR","TANAH LAUT","TANGERANG","TANGGAMUS","TANJUNG BALAI","TANJUNG JABUNG BARAT","TANJUNG JABUNG TIMUR","TANJUNG PINANG","TAPANULI SELATAN","TAPANULI TENGAH","TAPANULI UTARA","TARAKAN","TASIKMALAYA","TEBING TINGGI","TEBO","TEGAL","TELUK BINTUNI","TELUK WONDAMA","TEMANGGUNG","TENGGARONG","TERNATE","TIDORE","TILAMUTA","TIMOR TENGAH UTARA","TOBA SAMOSIR","TOJO UNA-UNA","TOLI-TOLI","TOLIKARA","TOMOHON","TORAJA UTARA","TRENGGALEK KOTA","TUAL","TUBAN","TULANG BAWANG","TULANG BAWANG BARAT","TULUNG AGUNG","UNGARAN","WAIBAKUL","WAIKABUBAK","WAINGAPU","WAJO","WAKATOBI","WAROPEN","WAY KANAN","WLINGI","WONOGIRI","WONOSARI","WONOSOBO","YAHUKIMO","YALIMO","YAPEN WAROPEN","YOGYAKARTA"]

    def get_areas(self, city):
        url = 'http://www.jet.co.id/droppoint/area'
        headers = {
            'X-CSRF-TOKEN': self.token,
        }
        data = {
            'city': city,
        }
        res = self.session.post(url, headers=headers, json=data)
        areas = [key for key in res.json().keys()]
        return areas

    def get_droppoints(self, city, area):
        url = 'http://www.jet.co.id/droppoint'
        data = {
            '_token': self.token,
            'droppoint-city': city,
            'droppoint-area': area,
        }
        res = self.session.post(url, json=data)

        # extract data from table
        droppoints = []
        soup = BeautifulSoup(res.text, "lxml")
        for row in soup.find('tbody').findAll('tr'):
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols][:-1]
            droppoints.append(cols)
        return droppoints

    def process_city(self, city):
        print ('Scrape {}...'.format(city))

        # scrape
        self.set_token()
        rows = []
        for area in self.get_areas(city):
            for droppoint in self.get_droppoints(city, area):
                droppoint.insert(0, area)
                droppoint.insert(0, city)
                rows.append(droppoint)

        # save output
        file_path = os.path.join(self.output_dir, '{}.csv'.format(city))
        df = pd.DataFrame(rows)
        df.to_csv(file_path, index=False, header=False, sep='~')

    def run(self):
        for city in self.get_cities():
            try:
                self.process_city(city)
            except Exception as e:
                print (e)
                pass
            time.sleep(1)

if __name__ == '__main__':
    DropPointScraper(
        output_dir='/Users/guangning.yu/Workspace/20190829_web_crawl/droppoints'
    ).run()
